import type {SystemConfig} from './systems';
export const keyMap:Record<string,number>={KeyF:17,KeyH:16,KeyG:18,KeyT:19,KeyJ:21,KeyL:20,KeyK:22,KeyI:23,KeyX:0,KeyZ:8,KeyA:1,KeyS:9,KeyQ:10,KeyE:11,Digit1:12,Digit3:13,ShiftLeft:2,ShiftRight:2,Enter:3,ArrowUp:4,ArrowDown:5,ArrowLeft:6,ArrowRight:7};
export const padMap:Record<number,number>={0:0,1:8,2:1,3:9,4:10,5:11,6:12,7:13,8:2,9:3,10:14,11:15,12:4,13:5,14:6,15:7};
export function parseInvite(raw:string){const u=new URL(raw,location.origin);const id=u.searchParams.get('room'),invite=new URLSearchParams(u.hash.slice(1)).get('key');if(!id||!/^[a-f0-9]{32}$/.test(id)||!invite||!/^[a-f0-9]{64}$/.test(invite))throw new Error('Paste the complete invite link, including the part after #.');return {id,invite};}
export async function validateFiles(files:File[],system?:SystemConfig){
 if(!files.length)throw new Error('Choose a game first.');
 const formats=system?.extensions||['bin','cue','chd','pbp','iso','img','zip','exe'];
 if(files.some(f=>!formats.includes(f.name.split('.').pop()!.toLowerCase())))throw new Error('Choose '+formats.map(f=>f.toUpperCase()).join(' / ')+' files.');
 if(files.some(f=>!f.size))throw new Error('A selected file is empty.');
 if(files.reduce((s,f)=>s+f.size,0)>1536*1048576)throw new Error('Keep game files under 1.5 GB for this browser player.');
 if(files.some(f=>f.name.includes('/')||f.name.includes('\\')))throw new Error('Select files directly from the game folder.');
 if(new Set(files.map(f=>f.name.toLowerCase())).size!==files.length)throw new Error('Two selected files have the same name.');
 if(files.length>1&&!files.some(f=>/\.cue$/i.test(f.name)))throw new Error('Choose one game image or ZIP, or a CUE with all of its tracks.');
 for(const cue of files.filter(f=>/\.cue$/i.test(f.name))){const text=await cue.text();const refs=[...text.matchAll(/FILE\s+(?:"([^"]+)"|(\S+))\s+/gi)];if(!refs.length)throw new Error('This CUE does not list any tracks.');for(const m of refs){const name=m[1]||m[2];if(!files.some(f=>f.name===name))throw new Error('Missing track: '+name+'. Select all tracks with the CUE.');}}
 if(files.some(f=>/\.(zip|chd|pbp|iso|exe)$/i.test(f.name))&&files.length>1)throw new Error('Select one game image or a CUE with its tracks.');
}
export async function packageDisc(files:File[],system?:SystemConfig){await validateFiles(files,system);if(files.length===1)return files[0];return packageFiles(files,files.find(f=>/\.cue$/i.test(f.name))!.name.replace(/\.cue$/i,'.zip'));}
// Store-only ZIP keeps exact filenames and avoids a second in-memory copy of every track.
export async function packageFiles(files:File[],archiveName:string){const encoder=new TextEncoder(),parts:BlobPart[]=[],central:BlobPart[]=[];let offset=0,centralSize=0;const table=new Uint32Array(256);for(let i=0;i<256;i++){let n=i;for(let b=0;b<8;b++)n=(n&1)?(0xedb88320^(n>>>1)):(n>>>1);table[i]=n;}for(const file of files){const name=encoder.encode(file.name),bytes=new Uint8Array(await file.arrayBuffer());let crc=0xffffffff;for(const b of bytes)crc=table[(crc^b)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30+name.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,file.size,true);v.setUint32(22,file.size,true);v.setUint16(26,name.length,true);h.set(name,30);parts.push(h,file);const c=new Uint8Array(46+name.length),w=new DataView(c.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,crc,true);w.setUint32(20,file.size,true);w.setUint32(24,file.size,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);c.set(name,46);central.push(c);centralSize+=c.length;offset+=h.length+file.size;}const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new File([...parts,...central,end],archiveName,{type:'application/zip'});}
